import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Trend, Counter } from 'k6/metrics';
import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

/**
 * Toy Board — realistic mixed-workload scenario.
 *
 * Workload mix (roughly): 60% list/read, 20% hot, 10% like toggle,
 * 7% comment, 3% article create. Thinks between actions.
 *
 * Env:
 *   BASE_URL       (default http://localhost:8080)
 *   BOARD_ID       (default 1)
 *   LIKE_STRATEGY  (default pessimistic-lock-2)
 *   MAX_USER_ID    (default 1000)
 */

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const BOARD_ID = Number(__ENV.BOARD_ID || 1);
const LIKE_STRATEGY = __ENV.LIKE_STRATEGY || 'pessimistic-lock-2';
const MAX_USER_ID = Number(__ENV.MAX_USER_ID || 1000);

const listTrend = new Trend('board_list_duration', true);
const readTrend = new Trend('board_read_duration', true);
const writeCounter = new Counter('board_writes');

export const options = {
  discardResponseBodies: false,
  scenarios: {
    browse: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '30s', target: 20 },
        { duration: '1m',  target: 50 },
        { duration: '2m',  target: 50 },
        { duration: '30s', target: 0  },
      ],
      gracefulRampDown: '10s',
      exec: 'browse',
    },
  },
  thresholds: {
    http_req_failed:   ['rate<0.02'],
    http_req_duration: ['p(95)<500', 'p(99)<1500'],
    board_list_duration: ['p(95)<400'],
    board_read_duration: ['p(95)<400'],
  },
};

function ymd(d = new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}${m}${day}`;
}

function pickArticleId(listJson) {
  const arr = listJson && listJson.articles;
  if (!Array.isArray(arr) || arr.length === 0) return null;
  const pick = arr[randomIntBetween(0, arr.length - 1)];
  return pick && pick.articleId;
}

export function browse() {
  const userId = randomIntBetween(1, MAX_USER_ID);
  let lastArticleId = null;

  group('list articles', () => {
    const page = randomIntBetween(1, 5);
    const res = http.get(`${BASE_URL}/v1/articles?boardId=${BOARD_ID}&page=${page}&pageSize=10`,
      { tags: { name: 'GET /v1/articles' } });
    check(res, { 'list 200': (r) => r.status === 200 });
    listTrend.add(res.timings.duration);
    try { lastArticleId = pickArticleId(res.json()); } catch (_) {}
  });

  sleep(randomIntBetween(1, 2));

  group('hot articles', () => {
    if (Math.random() < 0.35) {
      const res = http.get(`${BASE_URL}/v1/hot-articles/articles/date/${ymd()}`,
        { tags: { name: 'GET /v1/hot-articles' } });
      check(res, { 'hot 200': (r) => r.status === 200 });
    }
  });

  if (lastArticleId) {
    group('read article', () => {
      const res = http.get(`${BASE_URL}/v1/articles/${lastArticleId}?userId=${userId}`,
        { tags: { name: 'GET /v1/articles/{id}' } });
      check(res, { 'read 200': (r) => r.status === 200 });
      readTrend.add(res.timings.duration);
    });

    sleep(1);

    group('list comments', () => {
      const res = http.get(`${BASE_URL}/v2/comments?articleId=${lastArticleId}&page=1&pageSize=20`,
        { tags: { name: 'GET /v2/comments' } });
      check(res, { 'comments 200': (r) => r.status === 200 });
    });

    const dice = Math.random();

    if (dice < 0.10) {
      group('toggle like', () => {
        const url = `${BASE_URL}/v1/article-likes/articles/${lastArticleId}/users/${userId}/${LIKE_STRATEGY}`;
        const likeRes = http.post(url, null, { tags: { name: 'POST /v1/article-likes' } });
        check(likeRes, { 'like ok': (r) => r.status >= 200 && r.status < 300 || r.status === 409 });
        writeCounter.add(1);
        sleep(0.5);
        const unlikeRes = http.del(url, null, { tags: { name: 'DELETE /v1/article-likes' } });
        check(unlikeRes, { 'unlike ok': (r) => r.status >= 200 && r.status < 300 || r.status === 404 });
        writeCounter.add(1);
      });
    } else if (dice < 0.17) {
      group('create comment', () => {
        const body = JSON.stringify({ articleId: lastArticleId, writerId: userId, content: `load-test ${Date.now()}` });
        const res = http.post(`${BASE_URL}/v2/comments`, body,
          { headers: { 'Content-Type': 'application/json' }, tags: { name: 'POST /v2/comments' } });
        check(res, { 'comment created': (r) => r.status >= 200 && r.status < 300 });
        writeCounter.add(1);
      });
    } else if (dice < 0.20) {
      group('create article', () => {
        const body = JSON.stringify({
          boardId: BOARD_ID,
          writerId: userId,
          title: `load-test ${Date.now()}`,
          content: 'generated by k6 board-load.js',
        });
        const res = http.post(`${BASE_URL}/v1/articles`, body,
          { headers: { 'Content-Type': 'application/json' }, tags: { name: 'POST /v1/articles' } });
        check(res, { 'article created': (r) => r.status >= 200 && r.status < 300 });
        writeCounter.add(1);
      });
    }
  }

  sleep(randomIntBetween(1, 3));
}
