server:
  port: 8080
spring:
  application:
    name: toy-board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy_board?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379
